version: '3'

services:
  marketapi:
    build:
      context: ..
      dockerfile: docker/api.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../app:/app
    networks:
      - market_network
    depends_on:
      - marketdb

  marketdb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: market
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - market_network

networks:
  market_network:
    driver: bridge

volumes:
  mysql_data:
