version: '3'

services:
  api:
    build:
      context: ..
      dockerfile: docker/api.dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../app:/app
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: market
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
